apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cliniccare-staging

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: cliniccare
    patch: |-
      - op: replace
        path: /metadata/name
        value: cliniccare-staging
